# Generated by Django 4.2.5 on 2023-12-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=30)),
                ('Producto', models.CharField(max_length=30)),
                ('Cantidad', models.CharField(max_length=25)),
                ('Iva', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Valor_Venta', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
    ]
